;;; compiler.lisp --- faslout/faslend for Common Lisp REDUCE

;; Copyright (C) 2018 Francis J. Wright

;; Author: Francis J. Wright <https://sourceforge.net/u/fjwright>
;; Created: 15 December 2018

(declaim (optimize debug))				; same as (debug 3)
(declaim (sb-ext:muffle-conditions sb-ext:compiler-note style-warning))
;; (declaim (sb-ext:unmuffle-conditions sb-ext:compiler-note style-warning))

#-standard-lisp (load "sl-on-cl")
(in-package :standard-lisp)

(defvar *defn)
(defvar *writingfaslfile nil
  "REDUCE variable set to t by FASLOUT and reset to nil by FASLEND.")
(defvar *int)
(defvar *msg)
(defvar %%msg *msg
  "The current value of the msg switch, which is turned off during faslout.")

(defvar %%faslout-filehandle)
(defvar %%faslout-name.lisp)

(defun prettyprint (u)
  "Default print function, required for bootstrapping.
Redefined later."
  (print u))

(defun faslout (name)
  "Compile subsequent input into Common Lisp FASL file \"NAME.fasl\".
NAME should be an identifier or string.  (The actual extension of fasl
files depends on the version of Common Lisp.)"
  ;; Output subsequent code as Standard Lisp to a temporary file until
  ;; FASLEND evaluated.
  (setq name (string-downcase name))
  (if *int
	  (format t "FASLOUT ~a: IN files$ or type in expressions.
(Note that IN must be terminated by \"$\", not \";\"!)
When all done, execute FASLEND;~2%" name))
  (out_non_empty_list ; defined in rlisp/io -- used to avoid compiling prompt!
   (list (setq %%faslout-name.lisp (concat2 name ".sl"))))
  ;; If out_non_empty_list does not throw an error then...
  (setq *defn t
		*writingfaslfile t
		%%msg *msg
		*msg nil))

(flag '(faslout) 'opfn)
(flag '(faslout) 'noval)

;; SBCL outputs more detailed and useful messages than those that I
;; have therefore temporarily commented out below.  Delete them unless
;; they prove useful with other versions of Common Lisp.

(defun faslend ()
  "Terminate a previous FASLOUT and generate the compiled file."
  (unless *writingfaslfile
  	(cl:error "FASLEND is only allowed after a previous FASLOUT"))
  ;; First, tidy up after the call of FASLOUT:
  (shut_non_empty_list ; defined in rlisp/io -- used to avoid compiling prompt!
   (list %%faslout-name.lisp))
  (setq *msg %%msg
		*writingfaslfile nil
		*defn nil) ; necessary here if faslend not input as a statement
  ;; Now compile the Lisp output generated by FASLOUT:
  ;; (format t  "Compiling ~a..." %%faslout-name.lisp)
  ;; (if
  (compile-file %%faslout-name.lisp)
  ;; 	  ;; (progn
  ;; 	  ;; (delete-file %%faslout-name.lisp) ; keep to aid debugging ???
  ;; 	  (format t "Compiling ~a...done" %%faslout-name.lisp)
  ;; 	  ;; nil)
  ;; 	  (cl:error "Error compiling ~a" %%faslout-name.lisp))
  )

(defvar cursym*)

(defun faslendstat ()
  "Terminate reading faslend and turn defn off."
  ;; Modelled on endstat in rlisp/parser.
  (cl:let ((x cursym*))
	(setq *defn nil)					; must do this ASAP!
    (comm1 'end)
    (list x)))

(put 'faslend 'stat 'faslendstat)		; cf. endstat
(flag '(faslendstat) 'endstatfn)		; ditto

(flag '(faslend) 'ignore)				; to stop it getting compiled!

;;; compiler.lisp ends here
