#!/bin/bash
# Start ECL REDUCE on Cygwin, Linux or macOS.
export cl=$(realpath $(dirname $0)) # common-lisp directory, used in "reduce.lisp"
# echo 'cl =' $cl
ecl --eval "(let (*load-verbose*) (load \"$cl/fasl.ecl/reduce\"))"
