#!/bin/bash

# Start SBCL REDUCE on Cygwin, Linux or macOS.
# Author: Francis J. Wright <https://sourceforge.net/u/fjwright>
# Time-stamp: <2026-03-29 16:40:19 franc>

if [ "$1" = --help ]
then
    echo 'Start SBCL REDUCE on Cygwin, Linux or macOS.'
    echo 'Usage: redsbcl [--help] [other options] [--no-rcfile]'
    echo 'Useful options:'
    echo '  --help                     Print this message and exit.'
    echo '  --version                  Print SBCL version information and exit.'
    echo '  --control-stack-size <MiB> Size of reserved control stack; default 2.'
    echo '  --dynamic-space-size <MiB> Size of reserved dynamic space.'
    echo '  --no-rcfile                Inhibit REDUCE startup file.'
    exit
fi

cl=$(realpath $(dirname $0)) # common-lisp directory
if [ "$OSTYPE" == 'cygwin' ]; then cl=$(cygpath -m $cl); fi
exec sbcl --noinform --core $cl/fasl.sbcl/reduce.img $*

# SBCL runtime options should all work but not SBCL toplevel options,
# which are replaced by REDUCE options.  These are currently only
# --no-rcfile, which must appear after any runtime options.
